# Generated by Django 2.0.6 on 2020-07-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursediscount',
            options={'verbose_name': '价格优惠策略', 'verbose_name_plural': '价格优惠策略'},
        ),
        migrations.AlterModelTable(
            name='coursediscount',
            table='bz_course_discount',
        ),
    ]
